name: Feature Request
description: Suggest an idea
title: "[Feature Request]: "
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/EnAccess/Cicada-FW/blob/main/CONTRIBUTING.md) for this project, if it exists.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/EnAccess/Cicada-FW/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/EnAccess/Cicada-FW/issues) for a feature request that matches the one I want to file, without success.
          required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
    validations:
      required: false
