# Generic checks to ease collaboration:
# - consistent file encoding in UNIX style
# - whitespaces in all purposes files like markdown, yaml, etc
name: Check Generic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  editorconfig-checker:
    name: Run editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install editorconfig-checker
        run: pipx install "editorconfig-checker"
      - name: Run editorconfig-checker
        run: ec .

  markdownlint:
    name: Run markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v13

  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint .
